### ISSUE TITLE
Code that worked in initial release now fails with "luajit: not enough memory"

### ISSUE THREAD

**Issue by thouis** [twitter/torch-autograd#17] opened 2015-11-17 02:33 UTC
The example in this repository (currently at commit 6a03a4c)

https://github.com/thouis/denoise_cnn

Worked under the initial release (September 6, 2015).  After the newest release (September 16), it no longer works, getting an out of memory error when run.

This is on an 8GB macbook pro.

**Comment by clementfarabet** [comment] 2015-11-17 02:51
Just ran it: so it seems we're blowing up the internal LuaJIT limit of 2GB – @luketwitter could you look into this? We must be allocating a significant amount of temporary structures while building the graph. 

I was able to run your example ok with Lua 5.1, but I do get the mem crash with LuaJIT. 

Also it seems we've broken the number overloading, I had to replace your `0.5 * tensor` by `tensor * 0.5` to run it. Will look at that as well.

**Comment by thouis** [comment] 2015-11-17 14:04
This is off topic, but is there a simple way to switch between lua and luajit?  If not, I'll just revert to continue working in the meantime.

Thanks for the quick response to my report.

**Comment by clementfarabet** [comment] 2015-11-17 15:22
Then only way is to build Lua instead of LuaJIT, and then build re-install
every package against it. If you've installed torch from the distro repo (
https://github.com/torch/distro). The README tells you how to build against
Lua 5.1 instead of LuaJIT (the default).

**Comment by clementfarabet** [comment] 2015-11-17 19:43
cc @luketwitter @alexbw 

@thouis so re: memory issues. We're consuming slightly more mem, but not dramatically more. I think you got lucky that it ran before. The issue is that LuaJIT has a strict mem limit at 2GB for internal objects (tables, strings), which easily gets reached. Internally at Twitter we actually only use Lua, for this reason.

A recent patch was introduced in Torch though, to register a callback on malloc, which triggers a call to the GC, and fixes your problem. Simply add this at the top of your script: `torch.setheaptracking(true)`. @soumith : a remark on this, we've now enabled `torch.setheaptracking(true)` in our internal `th`; should we do the same in [torch/trepl](https://github.com/torch/trepl)? 

Re: operator issues. In autograd v1, we overloaded number operators globally, so that you could do things like `number * tensor` (which by default doesn't work). We've only enabled that for autograd compiled functions in v2, so you'll have to do `tensor * number` instead... but we feel like this should work all the time, so we might re-enable that globally, and I'd be tempted to move that feature to Torch itself.

**Comment by soumith** [comment] 2015-11-17 19:46
@clementfarabet thumbs up for enabling it in torch/trepl

**Comment by clementfarabet** [comment] 2015-11-17 20:01
@soumith great, just made a PR [here](https://github.com/torch/trepl/pull/44). 

btw, what's your process to update torch/distro?

**Comment by soumith** [comment] 2015-11-17 20:04
in torch/distro, run 
./update.sh
./clean.sh
./install.sh
./test.sh
git push

I'll do it now.

**Comment by clementfarabet** [comment] 2015-11-17 20:38
Neat, thanks!

**Comment by clementfarabet** [comment] 2015-11-17 21:07
Ok things should all be fixed now, with 2 updates:

```sh
luarocks install trepl
luarocks install autograd
th fcnn.lua z00000123_orig.png z00000123_labels.png
```

**Comment by alexbw** [comment] 2015-11-21 15:40
@thouis Does the fix above work for you?

**Comment by thouis** [comment] 2015-11-21 16:39
yes.

**Closed** 2015-11-21 16:44 UTC
